import * as React from 'react';
import { connect } from 'react-redux';
import { withPlaceholder, withSitecoreContext } from '@sitecore-jss/sitecore-jss-react';
class UIContent extends React.Component {
    render() {
        return (React.createElement(React.Fragment, null,
            React.createElement("section", { className: "content" },
                React.createElement("div", { className: "content__left" },
                    React.createElement("section", { className: "navigation" },
                        React.createElement("div", { className: "navigation__list" },
                            React.createElement("div", { className: "navigation__list__header", role: "button", "data-toggle": "collapse", "aria-expanded": "true", "aria-controls": "main" }, "Main"),
                            React.createElement("div", { className: "collapse in", id: "main" },
                                React.createElement("a", { href: "#", className: "navigation__list__item" },
                                    React.createElement("i", { className: "ion-ios-browsers" }),
                                    React.createElement("span", null, "Browse")),
                                React.createElement("a", { href: "#", className: "navigation__list__item" },
                                    React.createElement("i", { className: "ion-person-stalker" }),
                                    React.createElement("span", null, "Activity")),
                                React.createElement("a", { href: "#", className: "navigation__list__item" },
                                    React.createElement("i", { className: "ion-radio-waves" }),
                                    React.createElement("span", null, "Radio")))),
                        React.createElement("div", { className: "navigation__list" },
                            React.createElement("div", { className: "navigation__list__header", role: "button", "data-toggle": "collapse", "aria-expanded": "true", "aria-controls": "yourMusic" }, "Your Music"),
                            React.createElement("div", { className: "collapse in", id: "yourMusic" },
                                React.createElement("a", { href: "#", className: "navigation__list__item" },
                                    React.createElement("i", { className: "ion-headphone" }),
                                    React.createElement("span", null, "Songs")),
                                React.createElement("a", { href: "#", className: "navigation__list__item" },
                                    React.createElement("i", { className: "ion-ios-musical-notes" }),
                                    React.createElement("span", null, "Albums")),
                                React.createElement("a", { href: "#", className: "navigation__list__item" },
                                    React.createElement("i", { className: "ion-person" }),
                                    React.createElement("span", null, "Artists")),
                                React.createElement("a", { href: "#", className: "navigation__list__item" },
                                    React.createElement("i", { className: "ion-document" }),
                                    React.createElement("span", null, "Local Files")))),
                        React.createElement("div", { className: "navigation__list" },
                            React.createElement("div", { className: "navigation__list__header", role: "button", "data-toggle": "collapse", "aria-expanded": "true", "aria-controls": "playlists" }, "Playlists"),
                            this.props.playlist)),
                    React.createElement("section", { className: "playlist" },
                        React.createElement("a", { href: "#" },
                            React.createElement("i", { className: "ion-ios-plus-outline" }),
                            "New Playlist")),
                    React.createElement("section", { className: "playing" }, this.props.currentTrack ?
                        React.createElement(React.Fragment, null,
                            React.createElement("div", { className: "playing__art" },
                                React.createElement("img", { src: (this.props.album.images && this.props.album.images[0]) ? this.props.album.images[0].url : null, alt: this.props.album.name })),
                            React.createElement("div", { className: "playing__song" },
                                React.createElement("a", { className: "playing__song__name" }, this.props.currentTrack &&
                                    this.props.currentTrack.snippet &&
                                    this.props.currentTrack.snippet.title ? this.props.currentTrack.snippet.title.split('-')[1] : null),
                                React.createElement("a", { className: "playing__song__artist" }, this.props.artist.name)),
                            React.createElement("div", { className: "playing__add" },
                                React.createElement("i", { className: "ion-checkmark" })))
                        : null)),
                React.createElement("div", { className: "content__middle" },
                    React.createElement("div", { className: "artist is-verified" },
                        this.props.hero,
                        React.createElement("div", { className: "artist__content" },
                            React.createElement("div", { className: "tab-content" },
                                React.createElement("div", { role: "tabpanel", className: "tab-pane active", id: "artist-overview" },
                                    React.createElement("div", { className: "overview" },
                                        React.createElement("div", { className: "overview__artist" },
                                            this.props.albums,
                                            React.createElement("button", { className: "show-more button-light" }, "Show 5 More")),
                                        React.createElement("div", { className: "overview__related" },
                                            React.createElement("div", { className: "section-title" }, "Related Artists"),
                                            this.props.relatedArtists),
                                        React.createElement("div", { className: "overview__albums" }, this.props.album && this.props.album.images ?
                                            React.createElement(React.Fragment, null,
                                                React.createElement("div", { className: "overview__albums__head" },
                                                    React.createElement("span", { className: "section-title" }, "Albumm"),
                                                    React.createElement("span", { className: "view-type" },
                                                        React.createElement("i", { className: "fa fa-list list active" }),
                                                        React.createElement("i", { className: "fa fa-th-large card" }))),
                                                React.createElement("div", { className: "album" },
                                                    React.createElement("div", { className: "album__info" },
                                                        React.createElement("div", { className: "album__info__art" },
                                                            React.createElement("img", { src: (this.props.album.images && this.props.album.images[1]) ? this.props.album.images[1].url : null, alt: this.props.artist.name })),
                                                        React.createElement("div", { className: "album__info__meta" },
                                                            React.createElement("div", { className: "album__year" }, "2015"),
                                                            React.createElement("div", { className: "album__name" }, this.props.album.name),
                                                            React.createElement("div", { className: "album__actions" },
                                                                React.createElement("button", { className: "button-light save" }, "Save"),
                                                                React.createElement("button", { className: "button-light more" },
                                                                    React.createElement("i", { className: "ion-ios-more" }))))),
                                                    React.createElement("div", { className: "album__tracks" },
                                                        React.createElement("div", { className: "tracks" },
                                                            React.createElement("div", { className: "tracks__heading" },
                                                                React.createElement("div", { className: "tracks__heading__number" }, "#"),
                                                                React.createElement("div", { className: "tracks__heading__title" }, "Song"),
                                                                React.createElement("div", { className: "tracks__heading__length" },
                                                                    React.createElement("i", { className: "ion-ios-stopwatch-outline" })),
                                                                React.createElement("div", { className: "tracks__heading__popularity" },
                                                                    React.createElement("i", { className: "ion-thumbsup" }))),
                                                            this.props.tracklist))))
                                            : null))),
                                React.createElement("div", { role: "tabpanel", className: "tab-pane", id: "related-artists" },
                                    React.createElement("div", { className: "media-cards" },
                                        React.createElement("div", { className: "media-card" },
                                            React.createElement("div", { className: "media-card__image", style: { backgroundImage: "url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/7022/hoodie.jpg)" } },
                                                React.createElement("i", { className: "ion-ios-play" })),
                                            React.createElement("a", { className: "media-card__footer" }, "Hoodie Allen")),
                                        React.createElement("div", { className: "media-card" },
                                            React.createElement("div", { className: "media-card__image", style: { backgroundImage: "url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/7022/mikestud_large.jpg)" } },
                                                React.createElement("i", { className: "ion-ios-play" })),
                                            React.createElement("a", { className: "media-card__footer" }, "Mike Stud")),
                                        React.createElement("div", { className: "media-card" },
                                            React.createElement("div", { className: "media-card__image", style: { backgroundImage: "url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/7022/drake_large.jpg)" } },
                                                React.createElement("i", { className: "ion-ios-play" })),
                                            React.createElement("a", { className: "media-card__footer" }, "Drake")),
                                        React.createElement("div", { className: "media-card" },
                                            React.createElement("div", { className: "media-card__image", style: { backgroundImage: "url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/7022/jcole_large.jpg)" } },
                                                React.createElement("i", { className: "ion-ios-play" })),
                                            React.createElement("a", { className: "media-card__footer" }, "J. Cole")),
                                        React.createElement("div", { className: "media-card" },
                                            React.createElement("div", { className: "media-card__image", style: { backgroundImage: "url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/7022/bigSean_large.jpg)" } },
                                                React.createElement("i", { className: "ion-ios-play" })),
                                            React.createElement("a", { className: "media-card__footer" }, "Big Sean")),
                                        React.createElement("div", { className: "media-card" },
                                            React.createElement("div", { className: "media-card__image", style: { backgroundImage: "url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/7022/wiz.jpeg)" } },
                                                React.createElement("i", { className: "ion-ios-play" })),
                                            React.createElement("a", { className: "media-card__footer" }, "Wiz Khalifa")),
                                        React.createElement("div", { className: "media-card" },
                                            React.createElement("div", { className: "media-card__image", style: { backgroundImage: "url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/7022/yonas.jpg)" } },
                                                React.createElement("i", { className: "ion-ios-play" })),
                                            React.createElement("a", { className: "media-card__footer" }, "Yonas")),
                                        React.createElement("div", { className: "media-card" },
                                            React.createElement("div", { className: "media-card__image", style: { backgroundImage: "url(https://s3-us-west-2.amazonaws.com/s.cdpn.io/7022/childish.jpg)" } },
                                                React.createElement("i", { className: "ion-ios-play" })),
                                            React.createElement("a", { className: "media-card__footer" }, "Childish Gambino")))),
                                React.createElement("div", { role: "tabpanel", className: "tab-pane", id: "artist-about" }, "About"))))),
                React.createElement("div", { className: "content__right" },
                    React.createElement("div", { className: "social" },
                        React.createElement("div", { className: "friends" },
                            React.createElement("a", { href: "#", className: "friend" },
                                React.createElement("i", { className: "ion-android-person" }),
                                "Sam Smith"),
                            React.createElement("a", { href: "#", className: "friend" },
                                React.createElement("i", { className: "ion-android-person" }),
                                "Tarah Forsyth"),
                            React.createElement("a", { href: "#", className: "friend" },
                                React.createElement("i", { className: "ion-android-person" }),
                                "Ricahrd Tomkins"),
                            React.createElement("a", { href: "#", className: "friend" },
                                React.createElement("i", { className: "ion-android-person" }),
                                "Tony Russo"),
                            React.createElement("a", { href: "#", className: "friend" },
                                React.createElement("i", { className: "ion-android-person" }),
                                "Alyssa Marist"),
                            React.createElement("a", { href: "#", className: "friend" },
                                React.createElement("i", { className: "ion-android-person" }),
                                "Ron Samson")),
                        React.createElement("button", { className: "button-light" }, "Find Friends"))))));
    }
}
const mapStateToProps = (state) => {
    return {
        artist: state.artist,
        tracks: state.tracks,
        album: state.album,
        currentTrack: state.tracks.currentTrack,
    };
};
const mapDispatchToProps = (dispatch) => {
    return {};
};
const withPlaceholderInjected = withPlaceholder([
    {
        placeholder: 'jss-hero',
        prop: 'hero',
    },
    {
        placeholder: 'jss-albums',
        prop: 'albums',
    },
    {
        placeholder: 'jss-related-artists',
        prop: 'relatedArtists',
    },
    {
        placeholder: 'jss-tracklist',
        prop: 'tracklist',
    },
    {
        placeholder: 'jss-playlist',
        prop: 'playlist',
    }
])(UIContent);
const withPlaceholderAndSitecoreContext = withSitecoreContext()(withPlaceholderInjected);
export default connect(mapStateToProps, mapDispatchToProps)(withPlaceholderAndSitecoreContext);
